### PR TITLE
Start Sequelize integration

### PR DESCRIPTION
**Pull request by NathanBland**
Let's see how this PR goes..

@crodeheaver @keawade

### CODE REVIEW

**Comment by keawade** [comment]
We should probably try to use ES6/TS `import` wherever we can instead of `require`.

**Comment by NathanBland** [comment]
`require` is native to `node` so in this case there is no reason not to use it.

EDIT: As far as I can tell `import/export` isn't natively supported anywhere yet other than chrome. Meaning for everything else it is getting translated back to require..

EDIT2: More info can be found [here](http://2ality.com/2017/09/native-esm-node.html) but basically without babel they can be used *only* with a flag.

**Comment by keawade** [comment]
Sorry, I should have clarified that this is about TypeScript, specifically.

TypeScript uses the `import` syntax to pull the declaration files. Using `const thing = require('thing')` won't pull those definitions.

https://www.typescriptlang.org/docs/handbook/modules.html#import
https://stackoverflow.com/a/39658366
https://stackoverflow.com/a/35706271

**Comment by NathanBland** [comment]
This makes me grouchy as it is requiring *another* step to eventually lead back to `require`....

**Comment by keawade** [comment]
@NathanBland, @crodeheaver, I think we can merge this now. :tada:

**Review by keawade — APPROVED** [review]

**Pull request merged**
